#!/bin/bash

set -e

VERSION_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+$'

current_tag_version=`head -1 ./TAG_VERSION`

if [[ ! $current_tag_version =~ $VERSION_PATTERN ]]
then
  echo "Errore: Usa tipo '1.23.21'"
  exit 1
fi

# IFS Internal Field Separator
IFS="." read -r major minor patch <<< $current_tag_version
new_patch=$((patch + 1))
new_tag_version="$major.$minor.$new_patch"

echo $new_tag_version > ./TAG_VERSION

git commit -m 'tag version' TAG_VERSION
git tag "v$new_tag_version"
git push origin "v$new_tag_version"

echo "AGGIRNATO alla tag $new_tag_version il repo (e di conseguenza l'immagine)"
